name: Build Extension with Node.js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Chrome extension
        run: pnpm build

      - name: Upload Chrome extension
        uses: actions/upload-artifact@v7
        with:
          name: bys-chrome-${{ github.sha }}
          path: dist

      - name: Build Firefox extension
        run: npm run build:firefox -- --skip-build

      - name: Upload Firefox extension
        uses: actions/upload-artifact@v7
        with:
          name: bys-firefox-${{ github.sha }}
          path: dist
